package main

import (
	"context"
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/google/go-github/v57/github"
	"golang.org/x/oauth2"
)

type PRCreator struct {
	client    *github.Client
	repoOwner string
	repoName  string
}

func NewPRCreator(token, repoOwner, repoName string) *PRCreator {
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: token},
	)
	tc := oauth2.NewClient(ctx, ts)
	client := github.NewClient(tc)

	return &PRCreator{
		client:    client,
		repoOwner: repoOwner,
		repoName:  repoName,
	}
}

// CreateTestPR creates a new PR with generated test content
func (pc *PRCreator) CreateTestPR(ctx context.Context, sourceFile, testFile, testContent, branchName string, coverage float64) error {
	// Check if test file already exists
	existingFile, err := pc.getFileContent(ctx, testFile)
	if err == nil && existingFile != nil {
		// File exists, update it
		return pc.updateExistingTestFile(ctx, sourceFile, testFile, testContent, branchName, coverage, existingFile)
	}

	// File doesn't exist, create new one
	return pc.createNewTestFile(ctx, sourceFile, testFile, testContent, branchName, coverage)
}

// createNewTestFile creates a new test file and PR
func (pc *PRCreator) createNewTestFile(ctx context.Context, sourceFile, testFile, testContent, branchName string, coverage float64) error {
	// Get the default branch
	repo, _, err := pc.client.Repositories.Get(ctx, pc.repoOwner, pc.repoName)
	if err != nil {
		return fmt.Errorf("failed to get repository info: %v", err)
	}

	defaultBranch := repo.GetDefaultBranch()

	// Get the latest commit SHA of the default branch
	ref, _, err := pc.client.Git.GetRef(ctx, pc.repoOwner, pc.repoName, "refs/heads/"+defaultBranch)
	if err != nil {
		return fmt.Errorf("failed to get reference: %v", err)
	}

	// Create new branch
	newRef := &github.Reference{
		Ref: github.String("refs/heads/" + branchName),
		Object: &github.GitObject{
			SHA: ref.Object.SHA,
		},
	}

	_, _, err = pc.client.Git.CreateRef(ctx, pc.repoOwner, pc.repoName, newRef)
	if err != nil {
		return fmt.Errorf("failed to create branch: %v", err)
	}

	// Create the test file
	fileOptions := &github.RepositoryContentFileOptions{
		Message: github.String(fmt.Sprintf("Add auto-generated tests for %s\n\nGenerated by KubeEdge Auto Test Generator\nOriginal coverage: %.2f%%", sourceFile, coverage)),
		Content: []byte(testContent),
		Branch:  github.String(branchName),
	}

	_, _, err = pc.client.Repositories.CreateFile(ctx, pc.repoOwner, pc.repoName, testFile, fileOptions)
	if err != nil {
		return fmt.Errorf("failed to create file: %v", err)
	}

	// Create pull request
	prTitle := fmt.Sprintf("Add auto-generated tests for %s", filepath.Base(sourceFile))
	prBody := pc.buildPRDescription(sourceFile, coverage, false)

	pr := &github.NewPullRequest{
		Title: github.String(prTitle),
		Head:  github.String(branchName),
		Base:  github.String(defaultBranch),
		Body:  github.String(prBody),
	}

	createdPR, _, err := pc.client.PullRequests.Create(ctx, pc.repoOwner, pc.repoName, pr)
	if err != nil {
		return fmt.Errorf("failed to create pull request: %v", err)
	}

	// Add labels
	labels := []string{"auto-generated", "tests", "low-coverage"}
	_, _, err = pc.client.Issues.AddLabelsToIssue(ctx, pc.repoOwner, pc.repoName, createdPR.GetNumber(), labels)
	if err != nil {
		fmt.Printf("Warning: Failed to add labels to PR: %v\n", err)
	}

	// Add reviewers (get from OWNERS file)
	reviewers := pc.getReviewersFromOWNERS(ctx, sourceFile)
	if len(reviewers) > 0 {
		reviewersRequest := &github.ReviewersRequest{
			Reviewers: reviewers,
		}
		_, _, err = pc.client.PullRequests.RequestReviewers(ctx, pc.repoOwner, pc.repoName, createdPR.GetNumber(), *reviewersRequest)
		if err != nil {
			fmt.Printf("Warning: Failed to add reviewers to PR: %v\n", err)
		}
	}

	fmt.Printf("Created PR #%d: %s\n", createdPR.GetNumber(), prTitle)
	return nil
}

// updateExistingTestFile updates an existing test file with additional tests
func (pc *PRCreator) updateExistingTestFile(ctx context.Context, sourceFile, testFile, testContent, branchName string, coverage float64, existingFile *github.RepositoryContent) error {
	// Merge new tests with existing content
	existingContent, err := existingFile.GetContent()
	if err != nil {
		return fmt.Errorf("failed to get existing file content: %v", err)
	}

	mergedContent := pc.mergeTestContent(existingContent, testContent)

	// Get the default branch
	repo, _, err := pc.client.Repositories.Get(ctx, pc.repoOwner, pc.repoName)
	if err != nil {
		return fmt.Errorf("failed to get repository info: %v", err)
	}

	defaultBranch := repo.GetDefaultBranch()

	// Get the latest commit SHA of the default branch
	ref, _, err := pc.client.Git.GetRef(ctx, pc.repoOwner, pc.repoName, "refs/heads/"+defaultBranch)
	if err != nil {
		return fmt.Errorf("failed to get reference: %v", err)
	}

	// Create new branch
	newRef := &github.Reference{
		Ref: github.String("refs/heads/" + branchName),
		Object: &github.GitObject{
			SHA: ref.Object.SHA,
		},
	}

	_, _, err = pc.client.Git.CreateRef(ctx, pc.repoOwner, pc.repoName, newRef)
	if err != nil {
		return fmt.Errorf("failed to create branch: %v", err)
	}

	// Update the file
	fileOptions := &github.RepositoryContentFileOptions{
		Message: github.String(fmt.Sprintf("Update auto-generated tests for %s\n\nGenerated by KubeEdge Auto Test Generator\nOriginal coverage: %.2f%%", sourceFile, coverage)),
		Content: []byte(mergedContent),
		Branch:  github.String(branchName),
		SHA:     existingFile.SHA,
	}

	_, _, err = pc.client.Repositories.UpdateFile(ctx, pc.repoOwner, pc.repoName, testFile, fileOptions)
	if err != nil {
		return fmt.Errorf("failed to update file: %v", err)
	}

	// Create pull request
	prTitle := fmt.Sprintf("Update auto-generated tests for %s", filepath.Base(sourceFile))
	prBody := pc.buildPRDescription(sourceFile, coverage, true)

	pr := &github.NewPullRequest{
		Title: github.String(prTitle),
		Head:  github.String(branchName),
		Base:  github.String(defaultBranch),
		Body:  github.String(prBody),
	}

	createdPR, _, err := pc.client.PullRequests.Create(ctx, pc.repoOwner, pc.repoName, pr)
	if err != nil {
		return fmt.Errorf("failed to create pull request: %v", err)
	}

	fmt.Printf("Created update PR #%d: %s\n", createdPR.GetNumber(), prTitle)
	return nil
}

// getFileContent retrieves existing file content from repository
func (pc *PRCreator) getFileContent(ctx context.Context, filePath string) (*github.RepositoryContent, error) {
	fileContent, _, _, err := pc.client.Repositories.GetContents(ctx, pc.repoOwner, pc.repoName, filePath, nil)
	if err != nil {
		return nil, err
	}
	return fileContent, nil
}

// mergeTestContent intelligently merges new test content with existing tests
func (pc *PRCreator) mergeTestContent(existingContent, newContent string) string {
	// Parse existing content to find where to insert new tests
	newLines := strings.Split(newContent, "\n")

	// Find the package declaration and imports in new content
	var newTestFunctions []string
	inTestFunction := false
	var currentTestFunction strings.Builder

	for _, line := range newLines {
		trimmed := strings.TrimSpace(line)

		// Skip package declaration, imports, and copyright
		if strings.HasPrefix(trimmed, "package ") ||
			strings.HasPrefix(trimmed, "import ") ||
			strings.Contains(trimmed, "Copyright") ||
			trimmed == "" ||
			strings.HasPrefix(trimmed, "//") ||
			strings.HasPrefix(trimmed, "/*") ||
			strings.HasPrefix(trimmed, "*/") {
			continue
		}

		// Detect start of test function
		if strings.HasPrefix(trimmed, "func Test") || strings.HasPrefix(trimmed, "func Benchmark") {
			if inTestFunction && currentTestFunction.Len() > 0 {
				newTestFunctions = append(newTestFunctions, currentTestFunction.String())
			}
			currentTestFunction.Reset()
			inTestFunction = true
		}

		if inTestFunction {
			currentTestFunction.WriteString(line + "\n")

			// Check if this is the end of the function
			if trimmed == "}" && !strings.Contains(line, "if ") && !strings.Contains(line, "for ") {
				newTestFunctions = append(newTestFunctions, currentTestFunction.String())
				currentTestFunction.Reset()
				inTestFunction = false
			}
		}
	}

	// Add any remaining function
	if inTestFunction && currentTestFunction.Len() > 0 {
		newTestFunctions = append(newTestFunctions, currentTestFunction.String())
	}

	// Append new test functions to existing content
	result := existingContent
	if !strings.HasSuffix(result, "\n") {
		result += "\n"
	}

	result += "\n// Auto-generated tests added by KubeEdge Auto Test Generator\n"
	result += fmt.Sprintf("// Generated on: %s\n\n", time.Now().Format("2006-01-02 15:04:05"))

	for _, testFunc := range newTestFunctions {
		result += testFunc + "\n"
	}

	return result
}

// buildPRDescription creates a comprehensive PR description
func (pc *PRCreator) buildPRDescription(sourceFile string, coverage float64, isUpdate bool) string {
	var body strings.Builder

	if isUpdate {
		body.WriteString("## Auto-Generated Test Updates\n\n")
		body.WriteString(fmt.Sprintf("This PR contains automatically generated test updates for `%s`.\n\n", sourceFile))
	} else {
		body.WriteString("## Auto-Generated Unit Tests\n\n")
		body.WriteString(fmt.Sprintf("This PR contains automatically generated unit tests for `%s`.\n\n", sourceFile))
	}

	body.WriteString("### Coverage Information\n")
	body.WriteString(fmt.Sprintf("- **Original Coverage**: %.2f%%\n", coverage))
	body.WriteString("- **Coverage Threshold**: 40.00%%\n")
	if coverage < 40.0 {
		body.WriteString("- **Status**: Below threshold, tests generated\n\n")
	} else {
		body.WriteString("- **Status**: Additional tests generated for improved coverage\n\n")
	}

	body.WriteString("### Next Steps\n")
	body.WriteString("1. Review the generated tests for accuracy\n")
	body.WriteString("2. Run `make test PROFILE=y` to verify all tests pass\n")
	body.WriteString("3. Modify or add additional tests if needed\n")
	body.WriteString("4. Check coverage improvement with `make test PROFILE=y`\n")
	body.WriteString("5. Merge when tests are satisfactory\n\n")

	body.WriteString("### eneration Details\n")
	body.WriteString("- **Generator**: KubeEdge Auto Test Generator\n")
	body.WriteString("- **LLM**: Gemini 1.5 Flash\n")
	body.WriteString("- **Validation**: Simplified mode (no Docker validation)\n")
	body.WriteString("- **Framework Compliance**: gomonkey v2, testify, KubeEdge patterns\n\n")

	body.WriteString("---\n")
	body.WriteString("*This PR was automatically created by the KubeEdge Auto Test Generator workflow. ")
	body.WriteString("The tests have been generated and validated for basic Go syntax correctness.*")

	return body.String()
}

// getReviewersFromOWNERS reads OWNERS file to get appropriate reviewers
func (pc *PRCreator) getReviewersFromOWNERS(ctx context.Context, sourceFile string) []string {
	var reviewers []string

	// Try to find OWNERS file in the same directory
	dir := filepath.Dir(sourceFile)
	ownersPath := filepath.Join(dir, "OWNERS")

	content, err := pc.getFileContent(ctx, ownersPath)
	if err != nil {
		// Try parent directories
		parts := strings.Split(dir, "/")
		for i := len(parts) - 1; i >= 0; i-- {
			parentPath := strings.Join(parts[:i+1], "/")
			ownersPath = filepath.Join(parentPath, "OWNERS")
			content, err = pc.getFileContent(ctx, ownersPath)
			if err == nil {
				break
			}
		}
	}

	if err != nil {
		// Fallback to repository collaborators
		return pc.getRepositoryCollaborators(ctx)
	}

	// Parse OWNERS file content
	ownersContent, err := content.GetContent()
	if err != nil {
		return pc.getRepositoryCollaborators(ctx)
	}

	lines := strings.Split(ownersContent, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Skip comments and empty lines
		if strings.HasPrefix(line, "#") || line == "" {
			continue
		}

		// Look for GitHub usernames (typically prefixed with @)
		if strings.HasPrefix(line, "@") {
			username := strings.TrimPrefix(line, "@")
			username = strings.TrimSpace(username)
			if username != "" {
				reviewers = append(reviewers, username)
			}
		} else if strings.Contains(line, "reviewers:") || strings.Contains(line, "approvers:") {
			// YAML format parsing
			continue
		} else if !strings.Contains(line, ":") && !strings.Contains(line, " ") {
			// Plain username
			reviewers = append(reviewers, line)
		}
	}

	// Limit to maximum 3 reviewers to avoid spam
	if len(reviewers) > 3 {
		reviewers = reviewers[:3]
	}

	return reviewers
}

// getRepositoryCollaborators gets repository collaborators as fallback reviewers
func (pc *PRCreator) getRepositoryCollaborators(ctx context.Context) []string {
	collaborators, _, err := pc.client.Repositories.ListCollaborators(ctx, pc.repoOwner, pc.repoName, nil)
	if err != nil {
		return []string{}
	}

	var reviewers []string
	for _, collaborator := range collaborators {
		if collaborator.GetLogin() != "" {
			reviewers = append(reviewers, collaborator.GetLogin())
		}

		// Limit to maximum 2 collaborators
		if len(reviewers) >= 2 {
			break
		}
	}

	return reviewers
}

// CommentOnPR adds a comment to an existing PR
func (pc *PRCreator) CommentOnPR(ctx context.Context, prNumber, message string) error {
	if prNumber == "" {
		return nil // No PR to comment on
	}

	prNum, err := strconv.Atoi(prNumber)
	if err != nil {
		return fmt.Errorf("invalid PR number: %s", prNumber)
	}

	comment := &github.IssueComment{
		Body: github.String(message),
	}

	_, _, err = pc.client.Issues.CreateComment(ctx, pc.repoOwner, pc.repoName, prNum, comment)
	if err != nil {
		return fmt.Errorf("failed to create comment: %v", err)
	}

	return nil
}

// AddSuccessComment adds a success comment to the original PR
func (pc *PRCreator) AddSuccessComment(ctx context.Context, prNumber string, sourceFile string, testPRNumber int) error {
	if prNumber == "" {
		return nil
	}

	message := fmt.Sprintf(`**Auto Test Generation Successful!**

Successfully generated tests for %s

**Details:**
- Generated comprehensive unit tests
- Validated for basic Go syntax
- Following KubeEdge testing patterns
- Created PR #%d with the generated tests

**Next Steps:**
- Review the generated tests in PR #%d
- Tests are ready for review and merge

*Generated by KubeEdge Auto Test Generator*`, sourceFile, testPRNumber, testPRNumber)

	return pc.CommentOnPR(ctx, prNumber, message)
}

// AddFailureComment adds a failure comment to the original PR
func (pc *PRCreator) AddFailureComment(ctx context.Context, prNumber string, sourceFile string, attempts int, lastError error) error {
	if prNumber == "" {
		return nil
	}

	message := fmt.Sprintf(`❌ **Auto Test Generation Failed**

Failed to generate tests for `+"`%s`"+` after %d attempts.

**Last Error:**
`+"```"+`
%v
`+"```"+`

**Notification Sent:**
- Repository maintainers have been notified via GitHub issue
- Manual test creation may be required for this file

**Suggestions:**
- File may have complex dependencies requiring manual mocking
- Consider adding tests manually following KubeEdge patterns
- Check if the file needs refactoring for better testability

*Generated by KubeEdge Auto Test Generator*`, sourceFile, attempts, lastError)

	return pc.CommentOnPR(ctx, prNumber, message)
}

// CheckRateLimit checks GitHub API rate limit status
func (pc *PRCreator) CheckRateLimit(ctx context.Context) error {
	rateLimit, _, err := pc.client.RateLimits(ctx)
	if err != nil {
		return fmt.Errorf("failed to check rate limit: %v", err)
	}

	core := rateLimit.GetCore()
	if core.Remaining < 10 {
		resetTime := core.Reset.Format("15:04:05")
		return fmt.Errorf("GitHub API rate limit almost exceeded. Remaining: %d, Resets at: %s",
			core.Remaining, resetTime)
	}

	fmt.Printf("GitHub API rate limit: %d/%d remaining\n", core.Remaining, core.Limit)
	return nil
}

// GetRepository gets repository information
func (pc *PRCreator) GetRepository(ctx context.Context) (*github.Repository, error) {
	repo, _, err := pc.client.Repositories.Get(ctx, pc.repoOwner, pc.repoName)
	if err != nil {
		return nil, fmt.Errorf("failed to get repository: %v", err)
	}
	return repo, nil
}

// CreateTestsPR creates a pull request with generated tests (main interface method)
func (pc *PRCreator) CreateTestsPR(ctx context.Context, sourceFile string, testContent string, coverage float64) (int, error) {
	// Generate test file name and branch name
	testFile := pc.generateTestFileName(sourceFile)
	branchName := pc.generateBranchName(sourceFile)

	// Create the PR using existing method
	err := pc.CreateTestPR(ctx, sourceFile, testFile, testContent, branchName, coverage)
	if err != nil {
		return 0, err
	}

	// Since CreateTestPR doesn't return PR number, we need to get it
	// For now, return 0 to indicate success (the method logs the actual PR number)
	return 0, nil
}

// Helper methods for CreateTestsPR
func (pc *PRCreator) generateTestFileName(sourceFile string) string {
	dir := filepath.Dir(sourceFile)
	base := filepath.Base(sourceFile)
	name := strings.TrimSuffix(base, filepath.Ext(base))
	return filepath.Join(dir, name+"_test.go")
}

func (pc *PRCreator) generateBranchName(sourceFile string) string {
	cleanPath := strings.ReplaceAll(sourceFile, "/", "-")
	cleanPath = strings.ReplaceAll(cleanPath, ".", "-")
	timestamp := time.Now().Format("20060102-150405")
	return fmt.Sprintf("auto-test-generation-%s-%s", cleanPath, timestamp)
}
